In [0]:
print("hello world")

hello world

In [0]:
print("asdeidcanceiafjn")
import pandas as pd

asdeidcanceiafjn

In [0]:
my_dict = { 'name' : ["a", "b", "c", "d", "e","f", "g"],
                   'age' : [20,27, 35, 55, 18, 21, 35],
                   'designation': ["VP", "CEO", "CFO", "VP", "VP", "CEO", "MD"]}

In [0]:
df = pd.DataFrame(my_dict)

In [0]:
df

  name  age designation
0    a   20          VP
1    b   27         CEO
2    c   35         CFO
3    d   55          VP
4    e   18          VP
5    f   21         CEO
6    g   35          MD

In [0]:
df.to_csv('csv_example.csv')

In [0]:
from google.colab import files
files.download('csv_example.csv')

In [0]:
import pandas as pd
pd.array([1,2],dtype=int)

<PandasArray>
[1, 2]
Length: 2, dtype: int64

In [0]:
pd

In [0]:
import pandas as pd
 
XYZ_web= {'Day':[1,2,3,4,5,6], "Visitors":[1000, 700,6000,1000,400,350], "Bounce_Rate":[20,20, 23,15,10,34]}
 
df= pd.DataFrame(XYZ_web)
 
print(df)

   Day  Visitors  Bounce_Rate
0    1      1000           20
1    2       700           20
2    3      6000           23
3    4      1000           15
4    5       400           10
5    6       350           34

In [0]:
df.head(3)
df[0:3]

   Day  Visitors  Bounce_Rate
0    1      1000           20
1    2       700           20
2    3      6000           23

In [0]:
# importing pandas 
import pandas as pd 
  
# Creating new dataframe 
initial_data = {'First_name': ['Ram', 'Mohan', 'Tina', 'Jeetu', 'Meera'],  
                'Last_name': ['Kumar', 'Sharma', 'Ali', 'Gandhi', 'Kumari'],  
                'Marks': [12, 52, 36, 85, 23] } 
  
df = pd.DataFrame(initial_data, columns = ['First_name', 'Last_name', 'Marks']) 
  


result = [] 
for value in df["Marks"]: 
    if value >= 33: 
        result.append("Pass") 
    elif value < 0 and value > 100: 
        result.append("Invalid") 
    else: 
        result.append("Fail") 
       
df["Result"] = result    
print(df)

  First_name Last_name  Marks Result
0        Ram     Kumar     12   Fail
1      Mohan    Sharma     52   Pass
2       Tina       Ali     36   Pass
3      Jeetu    Gandhi     85   Pass
4      Meera    Kumari     23   Fail

In [0]:

pd.read_csv("csv_example.csv")

   Unnamed: 0 First_name Last_name  Marks Result
0           0        Ram     Kumar     12   Fail
1           1      Mohan    Sharma     52   Pass
2           2       Tina       Ali     36   Pass
3           3      Jeetu    Gandhi     85   Pass
4           4      Meera    Kumari     23   Fail

In [0]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]

In [0]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]

In [7]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
Modified array is:

NameError: ignored

In [20]:

a = np.arange(0,60,5)
b=a
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55

In [0]:
np.savetxt('first.csv',b)

In [22]:
np.loadtxt("first.csv")

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55.])